const PlayerActionTypes = {
  SET_PLAYER: 'SET_PLAYER',
  SET_QUESTION: 'SET_QUESTION',
  INIT_QUIZ_OPTIONS: 'INIT_QUIZ_OPTIONS',
  NAVIGATE_NEXT: 'NAVIGATE_NEXT',
  NAVIGATE_PREV: 'NAVIGATE_PREV',
  LOCK_QUESTION: 'LOCK_QUESTION',
  SAVE_OPTION: 'SAVE_OPTION',
  CLEAR_CURRENT_PAGE: 'CLEAR_CURRENT_PAGE',
  RESET_ALL: 'RESET_ALL',
};

export default PlayerActionTypes;
